#please download data file to work directory
Sys.setlocale("LC_TIME", "English")
dat <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
colnames(dat) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
png(file="plot3.png",width=480, height=480)
dateTime <- strptime( paste(dat$Date,dat$Time), format="%d/%m/%Y %H:%M:%S")
plot(dateTime,dat$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="",col="black")
lines(dateTime,dat$Sub_metering_2,type="l",col="red")
lines(dateTime,dat$Sub_metering_3,type="l",col="blue")
legend("topright", col = c("black", "red", "blue"), lty= 1,legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3") )
dev.off()